[tool.poetry]
name = "modeldeploy"
version = "0.1.0"
description = ""
authors = ["yen yung chin"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
